# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site language
lang: en-US

# Site title
title: "ASSOCIATION DIAE"

# A description of your site for meta tag, search engine results.
description: 

# The subpath of your site, e.g. /blog, for generating urls.
baseurl: ""

# The base hostname & protocol of your site for where absolute urls are needed.
url: "https://scriptor-jekyll.netlify.com"

# Favicon
favicon: images/favicon-32x32.png

# Google Analytics id, e.g. "UA-NNNNNNNN-N"
google_analytics: ""

# Site navigation - each item must have a title and a url.
navigation:
  - text: Accueil
    url: /


   

  - text: Qui somme-nous
    url: /about/
    submenuone : Qui somme-nous
    submenutwo : Mot du présidente
    submenuthre : Bureau Diae
    submenuoneurl : /quisommesnous/
    submenutwourl : /motdeprésidente/
    submenuthreurl : /about/
    submenu : 
      - text: test1
        url : /test/
  - text: Evenements
    url: /evenements/
  - text: Contact
    url: /contact/    


# The shortname for your Disqus site to enable comments.
disqus: justgoodthemes

# Colors
accent_color: '#ce2dd9'

# Site footer
footer:
  content: "&copy; Association DIAE all rights reserved. "
  has_social: true

# Plugins
plugins:
  - jekyll-paginate

# http://jekyllrb.com/docs/pagination/
paginate: 3
paginate_path: '/page:num/'


# Permalinks
permalink: /:title

# Conversion
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
